version: '3.7'

services:
  orion-api:
    container_name: orion-api
    image: orion-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4444:4444
    command: npm run start:dev
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: orion
      DB_CONNECTION_STRING: mysql://orion_root:j5m966qp7jiypfda@orion-mysql:3306
    networks:
      - orion-connect
  
  orion-mysql:
    container_name: orion-mysql
    image: mysql
    environment:
      MYSQL_USER: orion_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: orion
    ports:
      - 3306:3306
    volumes:
      - ~/docker/volumes/OrionApi_MySQL:/var/lib/mysql
    networks:
      - orion-connect
    logging:
      driver: none

networks:
  orion-connect:
    driver: bridge